# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'week11' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'FMDB'
  # pod 'FMDB/FTS'   # FMDB with FTS
  # pod 'FMDB/standalone'   # FMDB with latest SQLite amalgamation source
  # pod 'FMDB/standalone/FTS'   # FMDB with latest SQLite amalgamation source and FTS
  # pod 'FMDB/SQLCipher'   # FMDB with SQLCipher


  # Pods for week11

end
